[2023-07-31T13:20:55.389-0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testdag.task3_sql manual__2023-07-31T20:20:49.565751+00:00 [queued]>
[2023-07-31T13:20:55.391-0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testdag.task3_sql manual__2023-07-31T20:20:49.565751+00:00 [queued]>
[2023-07-31T13:20:55.391-0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-31T13:20:55.395-0700] {taskinstance.py:1327} INFO - Executing <Task(SQLExecuteQueryOperator): task3_sql> on 2023-07-31 20:20:49.565751+00:00
[2023-07-31T13:20:55.397-0700] {standard_task_runner.py:57} INFO - Started process 69890 to run task
[2023-07-31T13:20:55.399-0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'testdag', 'task3_sql', 'manual__2023-07-31T20:20:49.565751+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/testdag.py', '--cfg-path', '/var/folders/wq/wb1f6jvn7hs9kt8fvl1pjjf80000gn/T/tmpcvy0w3hp']
[2023-07-31T13:20:55.400-0700] {standard_task_runner.py:85} INFO - Job 52: Subtask task3_sql
[2023-07-31T13:20:55.415-0700] {task_command.py:410} INFO - Running <TaskInstance: testdag.task3_sql manual__2023-07-31T20:20:49.565751+00:00 [running]> on host sriharshas-macbook-pro.local
[2023-07-31T13:20:55.429-0700] {abstractoperator.py:594} ERROR - Exception rendering Jinja template for task 'task3_sql', field 'sql'. Template: 'testsqlquery.sql'
Traceback (most recent call last):
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: testsqlquery.sql
[2023-07-31T13:20:55.434-0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/sriharshabasiri/Library/Python/3.9/lib/python/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: testsqlquery.sql
[2023-07-31T13:20:55.440-0700] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=testdag, task_id=task3_sql, execution_date=20230731T202049, start_date=20230731T202055, end_date=20230731T202055
[2023-07-31T13:20:55.442-0700] {standard_task_runner.py:104} ERROR - Failed to execute job 52 for task task3_sql (testsqlquery.sql; 69890)
[2023-07-31T13:20:55.461-0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-31T13:20:55.469-0700] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
